spring:
  application:
    name: 'apisever'
  datasource:
    url: jdbc:mariadb://localhost:3306/springdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: springdbuser
    password: springdbuser
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 2000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 40MB
      enabled: true
      location: /workspace/uploads
      file-size-threshold: 1MB
  web:
    resources:
      static-locations: file:///workspace/uploads

logging:
  level:
    org.zerock: INFO

org:
  zerock:
    upload:
      folder: /workspace/uploads

server:
  address: 0.0.0.0
  port: 8080
